server:
  port: 80
  context-path: /weixin  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://localhost:3306/websocket  
    username: root  
    password: 123456

#配置日志
logging:
  file: log/wx.log
  level:
    roor: info